### ISSUE TITLE
Change UI for project details

### ISSUE THREAD

**Issue by acushlakoncept** [BravoClassic/mlh-team2-portfolio#4]
At the moment when you click on your project, it goes to the project detail page but from a UI perspective, it might look good if we can make the cards clickable where an overlay could pop up with all the information related to the project.
Or, perhaps we can also add an option to switch between these options.

**Comment by acushlakoncept** [comment]
I will start working on this issue

**Comment by BravoClassic** [comment]
Okay @acushlakoncept

**Comment by acushlakoncept** [comment]
I am trying to update one of your Project, is there any info you have I may add or simple delete the Placeholders:


## Inspiration

Using Ajax and PHP, I created a basic chatting application which allows users to message each other and search for other friends on the platform.

## What it does

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

## How we built it

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

## Challenge we ran into

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

**Comment by BravoClassic** [comment]
## What it does
It allows users on the platform to send and receive messages from each other in real-time.

## How it was built
I made use of HTML, CSS, and Javascript for the frontend. This enabled me to style the website and make Ajax calls using javascript to run my PHP code in the back end. PHP which was used in the backend allowed me to store data, and update data which made the site work. Real-time communicate was achieved by means of Ajax calls


## Challenge we ran into
I was faced with the issue of synchronizing the message between two users and using a notification of a new message on the users' page. 

@acushlakoncept here is my content✔

**Comment by acushlakoncept** [comment]
Thank you @BravoClassic 👍

**Comment by acushlakoncept** [comment]
Could you provide details for this too:

All Clean Ghana
Apr 2020 – Jan 2021

Project descriptionAll Clean Ghana is a project aimed at improving sanitation in market areas in Ghana. Currently, this project is targeted at renovating the current public toilet in Dome Market. All Clean Ghana participated in the Changemaker Global Pitch 2020 and received seed funding.

**Comment by BravoClassic** [comment]
## About the project
All Clean Ghana is a project aimed at improving sanitation in market areas in Ghana. Currently, this project is targeted at renovating the current public toilet in Dome Market. All Clean Ghana participated in the Changemaker Global Pitch 2020 and received seed funding. In this project, I improved sanitation at the market by fixing spoilt WC and refurbished the building by giving it a paint job.

@acushlakoncept let me know if you need any extra details ✅

**Comment by acushlakoncept** [comment]
Do you have any project screenshot?
